version: '4.33.1'

services:
  # MariaDB Database
  mariadb:
    build: 
      context: ./mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: github_data
      MYSQL_USER: Furkan
      MYSQL_PASSWORD: secret
      

    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend


  # Express Backend
  express:
    build:
      context: ./backend # Path to the Express Dockerfile
    container_name: express-backend
    volumes:
      - ./backend:/usr/src/app  # Bind mount the backend directory
      - /usr/src/app/node_modules  # Ignore the node_modules folder
    environment:
      DB_HOST: mariadb
      DB_USER: root
      DB_PASSWORD: secret
      DB_NAME: github_data
    ports:
      - "3000:3000"

    networks:
      - backend

networks:
  backend:

volumes:
  mariadb_data:

