# Use an official Node.js runtime as a parent image
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install -g nodemon
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose port
EXPOSE 3000

# Start the Express server
CMD ["nodemon", "server.js"]
